compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64

httpRetry: 3

httpTimeout: 600000

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.0.cjs
